"""
Django settings for gestor project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import pyodbc
from .dbrouter import DbRouter


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&w_knnp07-e#v)*(bztu1m@qh5g-*j939^6jc=!2zqfuloc6yz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['belesar','localhost','cachamuina','10.31.156.143']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main_app',
    'gestor',
    'vsad'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranetsaih.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranetsaih.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'gestor': {
        'ENGINE': 'mssql',
        'NAME': 'SAIHMS_GEST',
        'HOST': '10.31.156.184',
        'USER': 'django-user',
        'PASSWORD': 'CeCuSaIh2025',
        'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
            },
    },
     'hist': {
        'ENGINE': 'mssql',
        'NAME': 'SAIHMS_HIST',
        'HOST': '10.31.156.184',
        'USER': 'django-user',
        'PASSWORD': 'CeCuSaIh2025',
        'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
            },
    },
    'intranet': {
        'ENGINE': 'mssql',
        'NAME': 'SAIHMS_INTRANET',
        'HOST': '10.31.156.184',
        'USER': 'django-user',
        'PASSWORD': 'CeCuSaIh2025',
        'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
                'extra_params':"TrustServerCertificate=yes",                
            },
    },
    'web': {
        'ENGINE': 'mssql',
        'NAME': 'BD79188001',
        'HOST': '10.31.156.178',
        'USER': 'django-user',
        'PASSWORD': 'CeCuSaIh2025',
        'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
            },
    },
    'historica': {
        'ENGINE': 'mssql',
        'NAME': 'SAIHMS_HIST',
        'HOST': '10.31.156.184',
        'USER': 'django-user',
        'PASSWORD': 'CeCuSaIh2025',
        'OPTIONS': {
                'driver': 'ODBC Driver 18 for SQL Server',
                'Encrypt':'False'
            },
    },
    'vsad':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : 'FEWS_FORECAST',
        'HOST' : '10.31.156.174',
        'USER' : 'jorge',
        'PASSWORD': '0KDU1nod__'
    }
}

DATABASE_ROUTERS = ["intranetsaih.dbrouter.DbRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'CET'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/home/saihminosil/webapps/gestor-django/intranetsaih/static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
